name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.1, 3.2, 3.3, 3.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and Install Gem
        run: |
          gem build JunitTimingSplitter.gemspec && gem install junit_timing_splitter-1.1.0.gem
      - name: Run Tests
        run: ruby test/test_junit_timing_splitter.rb --verbose
